quarkus.http.port=8007
quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:payment_db}
quarkus.datasource.username=${DB_USER:airline}
quarkus.datasource.password=${DB_PASSWORD:postgres}
quarkus.hibernate-orm.database.generation=none

xendit.callback-token=${XENDIT_CALLBACK_TOKEN:dev-callback-token}

rabbitmq-host=${RABBITMQ_HOST:rabbitmq}
rabbitmq-port=${RABBITMQ_PORT:5672}
rabbitmq-username=${RABBITMQ_USERNAME:guest}
rabbitmq-password=${RABBITMQ_PASSWORD:guest}

mp.messaging.outgoing.payment-events.connector=smallrye-rabbitmq
mp.messaging.outgoing.payment-events.exchange.name=payment.events
mp.messaging.outgoing.payment-events.exchange.type=topic
mp.messaging.outgoing.payment-events.exchange.durable=true

%test.quarkus.rabbitmq.devservices.enabled=false
%test.quarkus.datasource.devservices.enabled=false
%test.quarkus.hibernate-orm.database.generation=drop-and-create
