quarkus.http.port=8008
quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:loyalty_db}
quarkus.datasource.username=${DB_USER:airline}
quarkus.datasource.password=${DB_PASSWORD:postgres}
quarkus.hibernate-orm.database.generation=none
