quarkus.http.port=8005
quarkus.application.name=booking-service

# Database
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER:airline}
quarkus.datasource.password=${DB_PASSWORD:postgres}
quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:booking_db}

quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=false
quarkus.hibernate-orm.physical-naming-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

# REST clients
quarkus.rest-client.passenger-api.url=${PASSENGER_SERVICE_URL:http://localhost:8001}
quarkus.rest-client.inventory-api.url=${INVENTORY_SERVICE_URL:http://localhost:8002}
quarkus.rest-client.pricing-api.url=${PRICING_SERVICE_URL:http://localhost:8006}
quarkus.rest-client.payment-api.url=${PAYMENT_SERVICE_URL:http://localhost:8007}

passenger.service.api-key=${PASSENGER_SERVICE_API_KEY:airline-internal-dev-key}

# RabbitMQ (reserved for future events)
rabbitmq-host=${RABBITMQ_HOST:localhost}
rabbitmq-port=${RABBITMQ_PORT:5672}

# Fix port 9000 conflict with MinIO
quarkus.grpc.server.port=9005
